### ISSUE TITLE
Unable to download segmentations : error HTTP 500 / (KeyError)

### ISSUE THREAD

**Issue by dreavjr** [ImageMarkup/isic-archive#319]
I'm getting an error when trying to download the segmentation masks, for IDs listed as existent for the images, e.g.:

https://isic-archive.com:443/api/v1/segmentation/55db081c9fc3c10470dba338

gives an error, but 

https://isic-archive.com:443/api/v1/segmentation?limit=50&offset=0&sort=created&sortdir=-1&imageId=559437af9fc3c13155146626

lists 55db081c9fc3c10470dba338 among the segmentations.

I'm observing the same phenomenon for several images.

**Comment by brianhelba** [comment]
Thanks for the report, @dreavjr . This issue should now be totally resolved by a combination of code changes and database migrations to the ISIC Archive.

FYI, we've done a few things recently:
* Store all segmentations internally as masks, making the `/segmentation/:id/mask` endpoint much faster, and resolving some server stability / service availability issues we were having when many segmentations were downloaded at once.
* Consolidate duplicate segmentations, so that multiple submissions of the same segmentation are now listed as additional `reviews` instead of separate segmentations. This will result in some segmentation IDs for duplicate segmentations no longer existing.
* Add additional internal checks to ensure all segmentations have a single contiguous region.
* Make the API return more information about the maximum skill of a segmentations' reviwers, and information about when a segmentation is `failed` (which just means a user has deliberately flagged that image as being too difficult to segment).

We're hoping to have more comprehensive documentation about the use and semantics of the API available soon, but I hope your immediate issues are now resolved.
